notes:
	latexmk -pdf notes.tex

clean:
	rm -f *~ *aux *acn *glo *ist *log *toc *bbl *bbl* *blg *ent *fls *fdb_latexmk *lot *lof *nav *out *snm *dvi *vrb *bcf *xml *alg *glg *acr *gls *rel *synctex.gz 

squeaky:
	rm -f *~ *pdf

paper:
	latexmk -pdf paper.tex

paperpub:
	latexmk -pdf paperpub.tex

manual:
	latexmk -pdf manual.tex